# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1j8BRvgNa9dkDwRytvL_8iniFNGluXsQ_
"""

from google.colab import files
uploaded=files.upload()

# Importing the required Libraries
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
# Loading the data into the Dataframe
df=pd.read_csv("datasets weather.csv")
df.head(5)

df.tail()

df.describe()

df.isnull().sum()

from sklearn import linear_model
x=df[['temp_max','temp_min']]
y=df['wind']
regr=linear_model.LinearRegression()
regr.fit(x,y)
predictedweather=regr.predict([[16.439083,8.234771]])
print("predictedweather[temp_max=16.439083,temp_min=8.234771]:")
print(predictedweather)

print("Coefficient [temp_max,temp_min]")
print(regr.coef_)

predictedweather=regr.predict([[22.200000,12.200000]])
print("predictedweather[temp_max=22.200000,temp_min=12.200000]:")
print(predictedweather)